EMAIL_MAX_LENGTH = 254
USERNAME_MAX_LENGTH = 150
FIRST_NAME_MAX_LENGTH = 150
LAST_NAME_MAX_LENGTH = 150
PASSWORD_MAX_LENGTH = 150
MIN_TIME_COOKING = 1
MAX_TIME_COOKING = 32000
MIN_INGREDIENT_AMOUNT = 1
MAX_INGREDIENT_AMOUNT = 1000
TAG_NAME_MAX_LENGTH = 200
TAG_SLUG_MAX_LENGTH = 200
INGREDIENT_NAME_MAX_LENGTH = 200
INGREDIENT_MU_MAX_LENGTH = 200
RECIPE_NAME_MAX_LENGTH = 200

USER_FIELDS = {
    'email': EMAIL_MAX_LENGTH,
    'username': USERNAME_MAX_LENGTH,
    'password': PASSWORD_MAX_LENGTH,
    'first_name': FIRST_NAME_MAX_LENGTH,
    'last_name': LAST_NAME_MAX_LENGTH,
}

RECIPE_FIELDS = [
    'tags',
    'ingredients',
    'name',
    'image',
    'text',
    'cooking_time',
]
