EMAIL_MAX_LENGTH = 254
USERNAME_MAX_LENGTH = PASSWORD_MAX_LENGTH = 150
FIRST_NAME_MAX_LENGTH = LAST_NAME_MAX_LENGTH = 150
MIN_TIME_COOKING = 1
MAX_TIME_COOKING = 32000
MIN_INGREDIENT_AMOUNT = 1
MAX_INGREDIENT_AMOUNT = 1000
TAG_NAME_MAX_LENGTH = TAG_SLUG_MAX_LENGTH = 200
INGREDIENT_NAME_MAX_LENGTH = INGREDIENT_MU_MAX_LENGTH = 200
RECIPE_NAME_MAX_LENGTH = 200
