# Generated by Django 4.2.8 on 2024-01-12 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='count',
            new_name='amount',
        ),
    ]
