# Generated by Django 4.2.8 on 2024-01-25 06:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_ingredientsrecipes_unique_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsrecipes',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Количество ингредиента'),
        ),
    ]
