# Generated by Django 4.2.8 on 2024-01-24 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_user_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='ingredient',
        ),
    ]
