# Generated by Django 4.2.8 on 2024-01-25 07:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_ingredientsrecipes_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(help_text='Введите время приготовления в минутах', validators=[django.core.validators.MinValueValidator(limit_value=1, message='Время приготовления не может быть меньше 1'), django.core.validators.MaxValueValidator(limit_value=32000, message='Время приготовления не может быть больше 32000')], verbose_name='Время приготовления'),
        ),
    ]
