# Generated by Django 4.2.8 on 2024-01-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_shoppingcart_unique_shopping_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='recipes/images/', verbose_name='Фото готового блюда'),
        ),
    ]
