name: Main Foodgram Workflow Test
on:
  push:
    branches:
      - master
jobs:
  checkout-and-print-tree:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code gonzilla  # Имя шага задаём сами
        uses: actions/checkout@v3 
      - name: Print project tree
        run: tree .
